dist: focal
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10
env:
  global:
    - CXX=g++-10
  jobs:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release
before_script:
  - cmake -E make_directory build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION ..
  - cmake --build .
script:
  - ctest --verbose
