language: cpp
before_install:
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install automake g++-4.9
before_script:
  - autoreconf -is
  - CXX=g++-4.9 ./configure
  - make
script:
  - make check
  - cat test/*.log
  - XM_LOG_FLAGS='--debug </dev/null' make check
  - cat test/*.log
