dist: bionic
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10
env:
  global:
    - CXX=g++-10
  jobs:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release
before_script:
  - cmake -E make_directory build
  - cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -S . -B build
  - cmake --build build
script:
  - cd build && ctest --verbose
