language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - automake
      - g++-5
before_script:
  - autoreconf -is
  - CXX=g++-5.3 ./configure
  - make
script:
  - make check
  - cat test/*.log
  - XM_LOG_FLAGS='--debug </dev/null' make check
  - cat test/*.log
