dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
before_script:
  - autoreconf -is
  - CXX=g++-8 ./configure
  - make
script:
  - make check
  - cat test/*.log
  - XM_LOG_FLAGS='--collector-threshold=0' make check
  - cat test/*.log
  - XM_LOG_FLAGS='--debug </dev/null' make check
  - cat test/*.log
