language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - automake
      - g++-7
before_install:
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get -qq update
  - sudo apt-get -qq install automake
before_script:
  - autoreconf -is
  - CXX=g++-7 ./configure
  - make
script:
  - make check
  - cat test/*.log
  - XM_LOG_FLAGS='--debug </dev/null' make check
  - cat test/*.log
