name: CMake
on: [push]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Debug, Release]
        include:
          - os: ubuntu-latest
            cxx: g++-10
    steps:
      - uses: actions/checkout@v2
      - name: Prepare vcpkg
        if: ${{matrix.os == 'windows-latest'}}
        run: vcpkg install libiconv:x64-windows
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        if: ${{matrix.os != 'windows-latest'}}
        env:
          CXX: ${{matrix.cxx}}
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
      - name: Configure CMake
        if: ${{matrix.os == 'windows-latest'}}
        working-directory: build
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"
      - name: Build
        working-directory: build
        run: cmake --build . --config ${{matrix.configuration}}
      - name: Test
        working-directory: build
        run: ctest -C ${{matrix.configuration}}
