name: CMake
on: [push]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Debug, Release]
        include:
          - os: ubuntu-latest
            cxx: g++-10
    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      env:
        CXX: ${{matrix.cxx}}
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build .
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.configuration}}
